name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tostamente
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/tostamente/jtosta:${{ github.sha }} .
          docker push gcr.io/tostamente/jtosta:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy jtosta \
            --image gcr.io/tostamente/jtosta:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated